// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/interfaces/rpc/inventorypb/inventory.proto

package inventorypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InventoryService_DeductBatch_FullMethodName  = "/inventory.v1.InventoryService/DeductBatch"
	InventoryService_RestockBatch_FullMethodName = "/inventory.v1.InventoryService/RestockBatch"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InventoryService 库存域对订单域开放的 RPC 契约。
// 契约变更规则:order 和 catalog 必须同一次提交里同步改,靠编译期报错保证两边一致。
type InventoryServiceClient interface {
	// DeductBatch 批量扣减库存,任一明细失败则整体失败(catalog 本地事务保证全有或全无)。
	// 幂等:同一 request_id 重复调用不重复扣减,返回首次的快照结果。
	DeductBatch(ctx context.Context, in *DeductBatchRequest, opts ...grpc.CallOption) (*DeductBatchResponse, error)
	// RestockBatch 批量回补库存(下单补偿 / 取消订单 / 超时取消共用)。
	// 幂等:同一 request_id 的回补只生效一次。
	RestockBatch(ctx context.Context, in *RestockBatchRequest, opts ...grpc.CallOption) (*RestockBatchResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) DeductBatch(ctx context.Context, in *DeductBatchRequest, opts ...grpc.CallOption) (*DeductBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductBatchResponse)
	err := c.cc.Invoke(ctx, InventoryService_DeductBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) RestockBatch(ctx context.Context, in *RestockBatchRequest, opts ...grpc.CallOption) (*RestockBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestockBatchResponse)
	err := c.cc.Invoke(ctx, InventoryService_RestockBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility.
//
// InventoryService 库存域对订单域开放的 RPC 契约。
// 契约变更规则:order 和 catalog 必须同一次提交里同步改,靠编译期报错保证两边一致。
type InventoryServiceServer interface {
	// DeductBatch 批量扣减库存,任一明细失败则整体失败(catalog 本地事务保证全有或全无)。
	// 幂等:同一 request_id 重复调用不重复扣减,返回首次的快照结果。
	DeductBatch(context.Context, *DeductBatchRequest) (*DeductBatchResponse, error)
	// RestockBatch 批量回补库存(下单补偿 / 取消订单 / 超时取消共用)。
	// 幂等:同一 request_id 的回补只生效一次。
	RestockBatch(context.Context, *RestockBatchRequest) (*RestockBatchResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInventoryServiceServer struct{}

func (UnimplementedInventoryServiceServer) DeductBatch(context.Context, *DeductBatchRequest) (*DeductBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductBatch not implemented")
}
func (UnimplementedInventoryServiceServer) RestockBatch(context.Context, *RestockBatchRequest) (*RestockBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestockBatch not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}
func (UnimplementedInventoryServiceServer) testEmbeddedByValue()                          {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	// If the following call panics, it indicates UnimplementedInventoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_DeductBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).DeductBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_DeductBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).DeductBatch(ctx, req.(*DeductBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_RestockBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestockBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).RestockBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_RestockBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).RestockBatch(ctx, req.(*RestockBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.v1.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeductBatch",
			Handler:    _InventoryService_DeductBatch_Handler,
		},
		{
			MethodName: "RestockBatch",
			Handler:    _InventoryService_RestockBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/interfaces/rpc/inventorypb/inventory.proto",
}
