// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/interfaces/rpc/inventorypb/inventory.proto

package inventorypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"` // SKU 编码仅商品内唯一,必须配合商品 ID 定位(与领域层约定一致)
	SkuCode       string                 `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductItem) Reset() {
	*x = DeductItem{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductItem) ProtoMessage() {}

func (x *DeductItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductItem.ProtoReflect.Descriptor instead.
func (*DeductItem) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *DeductItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductItem) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *DeductItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 订单侧生成,幂等与配对的锚点
	Items         []*DeductItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBatchRequest) Reset() {
	*x = DeductBatchRequest{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBatchRequest) ProtoMessage() {}

func (x *DeductBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBatchRequest.ProtoReflect.Descriptor instead.
func (*DeductBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *DeductBatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeductBatchRequest) GetItems() []*DeductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeductedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode       string                 `protobuf:"bytes,2,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"` // 名称快照,订单明细展示用
	UnitPrice     int64                  `protobuf:"varint,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`      // 单价快照,单位:分(与领域层 SKU.Price 一致)
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductedItem) Reset() {
	*x = DeductedItem{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductedItem) ProtoMessage() {}

func (x *DeductedItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductedItem.ProtoReflect.Descriptor instead.
func (*DeductedItem) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *DeductedItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeductedItem) GetSkuCode() string {
	if x != nil {
		return x.SkuCode
	}
	return ""
}

func (x *DeductedItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *DeductedItem) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *DeductedItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeductBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeductedItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductBatchResponse) Reset() {
	*x = DeductBatchResponse{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductBatchResponse) ProtoMessage() {}

func (x *DeductBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductBatchResponse.ProtoReflect.Descriptor instead.
func (*DeductBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeductBatchResponse) GetItems() []*DeductedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestockBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 复用对应 DeductBatch 的 request_id,实现配对与幂等
	Items         []*DeductItem          `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockBatchRequest) Reset() {
	*x = RestockBatchRequest{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockBatchRequest) ProtoMessage() {}

func (x *RestockBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockBatchRequest.ProtoReflect.Descriptor instead.
func (*RestockBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *RestockBatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RestockBatchRequest) GetItems() []*DeductItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type RestockBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestockBatchResponse) Reset() {
	*x = RestockBatchResponse{}
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestockBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestockBatchResponse) ProtoMessage() {}

func (x *RestockBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestockBatchResponse.ProtoReflect.Descriptor instead.
func (*RestockBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP(), []int{5}
}

var File_internal_interfaces_rpc_inventorypb_inventory_proto protoreflect.FileDescriptor

const file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDesc = "" +
	"\n" +
	"3internal/interfaces/rpc/inventorypb/inventory.proto\x12\finventory.v1\"b\n" +
	"\n" +
	"DeductItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x02 \x01(\tR\askuCode\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"c\n" +
	"\x12DeductBatchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.inventory.v1.DeductItemR\x05items\"\xa6\x01\n" +
	"\fDeductedItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x19\n" +
	"\bsku_code\x18\x02 \x01(\tR\askuCode\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x03R\tunitPrice\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"G\n" +
	"\x13DeductBatchResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.inventory.v1.DeductedItemR\x05items\"d\n" +
	"\x13RestockBatchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.inventory.v1.DeductItemR\x05items\"\x16\n" +
	"\x14RestockBatchResponse2\xbd\x01\n" +
	"\x10InventoryService\x12R\n" +
	"\vDeductBatch\x12 .inventory.v1.DeductBatchRequest\x1a!.inventory.v1.DeductBatchResponse\x12U\n" +
	"\fRestockBatch\x12!.inventory.v1.RestockBatchRequest\x1a\".inventory.v1.RestockBatchResponseBKZIgithub.com/wsc-zz/service/internal/interfaces/rpc/inventorypb;inventorypbb\x06proto3"

var (
	file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescOnce sync.Once
	file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescData []byte
)

func file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescGZIP() []byte {
	file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDesc), len(file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDesc)))
	})
	return file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDescData
}

var file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_interfaces_rpc_inventorypb_inventory_proto_goTypes = []any{
	(*DeductItem)(nil),           // 0: inventory.v1.DeductItem
	(*DeductBatchRequest)(nil),   // 1: inventory.v1.DeductBatchRequest
	(*DeductedItem)(nil),         // 2: inventory.v1.DeductedItem
	(*DeductBatchResponse)(nil),  // 3: inventory.v1.DeductBatchResponse
	(*RestockBatchRequest)(nil),  // 4: inventory.v1.RestockBatchRequest
	(*RestockBatchResponse)(nil), // 5: inventory.v1.RestockBatchResponse
}
var file_internal_interfaces_rpc_inventorypb_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.v1.DeductBatchRequest.items:type_name -> inventory.v1.DeductItem
	2, // 1: inventory.v1.DeductBatchResponse.items:type_name -> inventory.v1.DeductedItem
	0, // 2: inventory.v1.RestockBatchRequest.items:type_name -> inventory.v1.DeductItem
	1, // 3: inventory.v1.InventoryService.DeductBatch:input_type -> inventory.v1.DeductBatchRequest
	4, // 4: inventory.v1.InventoryService.RestockBatch:input_type -> inventory.v1.RestockBatchRequest
	3, // 5: inventory.v1.InventoryService.DeductBatch:output_type -> inventory.v1.DeductBatchResponse
	5, // 6: inventory.v1.InventoryService.RestockBatch:output_type -> inventory.v1.RestockBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_interfaces_rpc_inventorypb_inventory_proto_init() }
func file_internal_interfaces_rpc_inventorypb_inventory_proto_init() {
	if File_internal_interfaces_rpc_inventorypb_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDesc), len(file_internal_interfaces_rpc_inventorypb_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_rpc_inventorypb_inventory_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_rpc_inventorypb_inventory_proto_depIdxs,
		MessageInfos:      file_internal_interfaces_rpc_inventorypb_inventory_proto_msgTypes,
	}.Build()
	File_internal_interfaces_rpc_inventorypb_inventory_proto = out.File
	file_internal_interfaces_rpc_inventorypb_inventory_proto_goTypes = nil
	file_internal_interfaces_rpc_inventorypb_inventory_proto_depIdxs = nil
}
