// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: internal/interfaces/rpc/orderpb/orderPay.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderPayService_GetPayableOrder_FullMethodName = "/orderpay.v1.OrderPayService/GetPayableOrder"
	OrderPayService_NotifyPaid_FullMethodName      = "/orderpay.v1.OrderPayService/NotifyPaid"
)

// OrderPayServiceClient is the client API for OrderPayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderPayService 订单域对支付域开放的 RPC 契约。
// 契约变更规则:payment 和 order 必须同一次提交里同步改,靠编译期报错保证两边一致
type OrderPayServiceClient interface {
	// GetPayableOrder 查询订单(预支付前调用)。只做取数,归属与可付策略由 payment 裁决。
	GetPayableOrder(ctx context.Context, in *GetPayableOrderRequest, opts ...grpc.CallOption) (*GetPayableOrderResponse, error)
	// NotifyPaid 通知支付结果。
	// 幂等:订单已支付 → 返回成功(重放安全);
	// 订单已取消 → FailedPrecondition(payment 侧转"待退款");
	// 金额与订单总额不一致 → InvalidArgument(人工介入,绝不自动放行)。
	NotifyPaid(ctx context.Context, in *NotifyPaidRequest, opts ...grpc.CallOption) (*NotifyPaidResponse, error)
}

type orderPayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderPayServiceClient(cc grpc.ClientConnInterface) OrderPayServiceClient {
	return &orderPayServiceClient{cc}
}

func (c *orderPayServiceClient) GetPayableOrder(ctx context.Context, in *GetPayableOrderRequest, opts ...grpc.CallOption) (*GetPayableOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayableOrderResponse)
	err := c.cc.Invoke(ctx, OrderPayService_GetPayableOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderPayServiceClient) NotifyPaid(ctx context.Context, in *NotifyPaidRequest, opts ...grpc.CallOption) (*NotifyPaidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyPaidResponse)
	err := c.cc.Invoke(ctx, OrderPayService_NotifyPaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderPayServiceServer is the server API for OrderPayService service.
// All implementations must embed UnimplementedOrderPayServiceServer
// for forward compatibility.
//
// OrderPayService 订单域对支付域开放的 RPC 契约。
// 契约变更规则:payment 和 order 必须同一次提交里同步改,靠编译期报错保证两边一致
type OrderPayServiceServer interface {
	// GetPayableOrder 查询订单(预支付前调用)。只做取数,归属与可付策略由 payment 裁决。
	GetPayableOrder(context.Context, *GetPayableOrderRequest) (*GetPayableOrderResponse, error)
	// NotifyPaid 通知支付结果。
	// 幂等:订单已支付 → 返回成功(重放安全);
	// 订单已取消 → FailedPrecondition(payment 侧转"待退款");
	// 金额与订单总额不一致 → InvalidArgument(人工介入,绝不自动放行)。
	NotifyPaid(context.Context, *NotifyPaidRequest) (*NotifyPaidResponse, error)
	mustEmbedUnimplementedOrderPayServiceServer()
}

// UnimplementedOrderPayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderPayServiceServer struct{}

func (UnimplementedOrderPayServiceServer) GetPayableOrder(context.Context, *GetPayableOrderRequest) (*GetPayableOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayableOrder not implemented")
}
func (UnimplementedOrderPayServiceServer) NotifyPaid(context.Context, *NotifyPaidRequest) (*NotifyPaidResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPaid not implemented")
}
func (UnimplementedOrderPayServiceServer) mustEmbedUnimplementedOrderPayServiceServer() {}
func (UnimplementedOrderPayServiceServer) testEmbeddedByValue()                         {}

// UnsafeOrderPayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderPayServiceServer will
// result in compilation errors.
type UnsafeOrderPayServiceServer interface {
	mustEmbedUnimplementedOrderPayServiceServer()
}

func RegisterOrderPayServiceServer(s grpc.ServiceRegistrar, srv OrderPayServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderPayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderPayService_ServiceDesc, srv)
}

func _OrderPayService_GetPayableOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayableOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderPayServiceServer).GetPayableOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderPayService_GetPayableOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderPayServiceServer).GetPayableOrder(ctx, req.(*GetPayableOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderPayService_NotifyPaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderPayServiceServer).NotifyPaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderPayService_NotifyPaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderPayServiceServer).NotifyPaid(ctx, req.(*NotifyPaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderPayService_ServiceDesc is the grpc.ServiceDesc for OrderPayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderPayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderpay.v1.OrderPayService",
	HandlerType: (*OrderPayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayableOrder",
			Handler:    _OrderPayService_GetPayableOrder_Handler,
		},
		{
			MethodName: "NotifyPaid",
			Handler:    _OrderPayService_NotifyPaid_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/interfaces/rpc/orderpb/orderPay.proto",
}
