// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/interfaces/rpc/orderpb/orderPay.proto

package orderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPayableOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayableOrderRequest) Reset() {
	*x = GetPayableOrderRequest{}
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayableOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayableOrderRequest) ProtoMessage() {}

func (x *GetPayableOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayableOrderRequest.ProtoReflect.Descriptor instead.
func (*GetPayableOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescGZIP(), []int{0}
}

func (x *GetPayableOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type GetPayableOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        int64                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayableOrderResponse) Reset() {
	*x = GetPayableOrderResponse{}
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayableOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayableOrderResponse) ProtoMessage() {}

func (x *GetPayableOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayableOrderResponse.ProtoReflect.Descriptor instead.
func (*GetPayableOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescGZIP(), []int{1}
}

func (x *GetPayableOrderResponse) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *GetPayableOrderResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPayableOrderResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetPayableOrderResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type NotifyPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayNo         string                 `protobuf:"bytes,2,opt,name=pay_no,json=payNo,proto3" json:"pay_no,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaidRequest) Reset() {
	*x = NotifyPaidRequest{}
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaidRequest) ProtoMessage() {}

func (x *NotifyPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaidRequest.ProtoReflect.Descriptor instead.
func (*NotifyPaidRequest) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyPaidRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *NotifyPaidRequest) GetPayNo() string {
	if x != nil {
		return x.PayNo
	}
	return ""
}

func (x *NotifyPaidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type NotifyPaidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyPaidResponse) Reset() {
	*x = NotifyPaidResponse{}
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPaidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPaidResponse) ProtoMessage() {}

func (x *NotifyPaidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPaidResponse.ProtoReflect.Descriptor instead.
func (*NotifyPaidResponse) Descriptor() ([]byte, []int) {
	return file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescGZIP(), []int{3}
}

var File_internal_interfaces_rpc_orderpb_orderPay_proto protoreflect.FileDescriptor

const file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDesc = "" +
	"\n" +
	".internal/interfaces/rpc/orderpb/orderPay.proto\x12\vorderpay.v1\"3\n" +
	"\x16GetPayableOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\"\x88\x01\n" +
	"\x17GetPayableOrderResponse\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x03R\x06status\"]\n" +
	"\x11NotifyPaidRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x15\n" +
	"\x06pay_no\x18\x02 \x01(\tR\x05payNo\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\x14\n" +
	"\x12NotifyPaidResponse2\xbe\x01\n" +
	"\x0fOrderPayService\x12\\\n" +
	"\x0fGetPayableOrder\x12#.orderpay.v1.GetPayableOrderRequest\x1a$.orderpay.v1.GetPayableOrderResponse\x12M\n" +
	"\n" +
	"NotifyPaid\x12\x1e.orderpay.v1.NotifyPaidRequest\x1a\x1f.orderpay.v1.NotifyPaidResponseBCZAgithub.com/wsc-zz/service/internal/interfaces/rpc/orderpb;orderpbb\x06proto3"

var (
	file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescOnce sync.Once
	file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescData []byte
)

func file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescGZIP() []byte {
	file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescOnce.Do(func() {
		file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDesc), len(file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDesc)))
	})
	return file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDescData
}

var file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_interfaces_rpc_orderpb_orderPay_proto_goTypes = []any{
	(*GetPayableOrderRequest)(nil),  // 0: orderpay.v1.GetPayableOrderRequest
	(*GetPayableOrderResponse)(nil), // 1: orderpay.v1.GetPayableOrderResponse
	(*NotifyPaidRequest)(nil),       // 2: orderpay.v1.NotifyPaidRequest
	(*NotifyPaidResponse)(nil),      // 3: orderpay.v1.NotifyPaidResponse
}
var file_internal_interfaces_rpc_orderpb_orderPay_proto_depIdxs = []int32{
	0, // 0: orderpay.v1.OrderPayService.GetPayableOrder:input_type -> orderpay.v1.GetPayableOrderRequest
	2, // 1: orderpay.v1.OrderPayService.NotifyPaid:input_type -> orderpay.v1.NotifyPaidRequest
	1, // 2: orderpay.v1.OrderPayService.GetPayableOrder:output_type -> orderpay.v1.GetPayableOrderResponse
	3, // 3: orderpay.v1.OrderPayService.NotifyPaid:output_type -> orderpay.v1.NotifyPaidResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_interfaces_rpc_orderpb_orderPay_proto_init() }
func file_internal_interfaces_rpc_orderpb_orderPay_proto_init() {
	if File_internal_interfaces_rpc_orderpb_orderPay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDesc), len(file_internal_interfaces_rpc_orderpb_orderPay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_interfaces_rpc_orderpb_orderPay_proto_goTypes,
		DependencyIndexes: file_internal_interfaces_rpc_orderpb_orderPay_proto_depIdxs,
		MessageInfos:      file_internal_interfaces_rpc_orderpb_orderPay_proto_msgTypes,
	}.Build()
	File_internal_interfaces_rpc_orderpb_orderPay_proto = out.File
	file_internal_interfaces_rpc_orderpb_orderPay_proto_goTypes = nil
	file_internal_interfaces_rpc_orderpb_orderPay_proto_depIdxs = nil
}
